name: Fetch Google Trends

on:
  workflow_dispatch: {}
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Fetch Google Trends Realtime and build JSON
        run: node scripts/fetch-trends.mjs

      - name: Commit changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add public/data/trends_kr.json
            git commit -m "chore(data): update trends JSON"
            git push
          else
            echo "No changes to commit."
          fi
